MAIN_URL = 'https://stellarburgers.nomoreparties.site/'
LOGIN_PAGE = 'https://stellarburgers.nomoreparties.site/login'
FORGOT_PASSWORD_PAGE = 'https://stellarburgers.nomoreparties.site/forgot-password'
RESET_PASSWORD_PAGE = 'https://stellarburgers.nomoreparties.site/reset-password'
ORDER_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
ORDER_FEED = 'https://stellarburgers.nomoreparties.site/feed'